development:
  clients:
    default:
      database: poi-production
      hosts:
        - localhost: 27017
    poistat:
      database: poi-stat
      hosts:
        - localhost: 27017

production:
  clients:
    default:
      database: poi-production
      hosts:
        - localhost: 27017
    poistat:
      database: poi-stat
      hosts:
        - localhost: 27017
